apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault-unseal-controller-setup
  namespace: flux-system
spec:
  interval: 30m
  path: ./gitops/apps/vault-unseal-controller/setup
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault-unseal-controler-config
  namespace: flux-system
spec:
  interval: 30m
  path: ./gitops/apps/vault-unseal-controller/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
